### ISSUE TITLE
Corruption Tracking

### ISSUE THREAD

**Issue by brother-lucius** [schnick3rs/wang-charz#36]
See core, pg. 285

**Rules:**

> * Gained as part of Species, Archetype, Ascension, Talent or some Keywords
> * Gained during play
> * Every X (5) Corruption increase a level from 0-25
> * 26+ is chaos spawn
> 
> When exposed, Roll Conviction vs 3 (+1 per level), and +x by GM
> * Fail = +1 Corruption and 1 Ruin
> * Failed Complication = +2 Corruption and 1 Ruin
> * Crit = recude DN by 2
> * Spend Wrath to reduce DN by 1
> 
> When gaining a new Level -> Mutation Test
> * You may opt to fail the test
> * Roll Conviction vs DN 3 +1 per level
> * Fail grants you one table
> * Roll d66 for specific mutation, +10 for each existing mutation

---

**ToDos:**

* Option to modify Corruption VALUE
* SET Value
* Add Value (list each value, aka modifier)

- [x] Show Current Corruption Points
- [x] Add Corruption Points
- [x] Delete Corruption Points by Source (only custom)
- [x] Show Current Corruption Level
- [x] Add Mutation
- [x] Delete Mutation
